name: pytide
channels:
        - conda-forge
dependencies:
        - python=3.7.3
        - numpy=1.18.4
        - pandas=1.0.4
        - xarray=0.15.1
        - dask=2.9.0
        - distributed=2.9.0
        - netcdf4=1.5.3
        - zarr=2.4.0
        - jupyter=1.0.0
        - ipykernel=5.3.0
        - dask-jobqueue=0.7.0 
        - matplotlib=3.3.1
        - scipy=1.5.2
        - conda-pack=0.5.0
